### PR TITLE
(CLOUD-826) Agent upgrade

### PR DESCRIPTION
**Pull request by sheenaajay**
Request to review the changes to the image_build module.

image_build module is updated with latest agents.

Files modified image

modified:   lib/puppet_x/puppetlabs/imagebuilder.rb
modified:   lib/puppet_x/puppetlabs/imagebuilder_face.rb

### CODE REVIEW

**Comment by gregohardy** [comment]
+1

**Comment by garethr** [comment]
@sheenaajay this PR is against your own branch rather than the upstream

**Comment by garethr** [comment]
@sheenaajay if you could change the commit message to explain the change. Drop the `Maint` portion as you have a Jira indicator. Also don't repeat the name of the project in the commit, it's not needed.

Other than that looks good once it's retargeted.

**Comment by sheenaajay** [comment]
@garethr .Thanks for the review comments.Changed the commit message to (CLOUD-826) Agent upgrade.Pushing changes to upstream.

**Pull request closed without merging**
